### ISSUE TITLE
Get the decoded message's schema ID

### ISSUE THREAD

**Issue by ThomasFerro** [kafkajs/confluent-schema-registry#105]
Hi !

In the `SchemaRegistry.ts`'s `decode` method, you get access to the `registryId` used to encore the message. We would like to have this information to apply the right data migration strategy.

Is there a way to access this data in the current version?

If not, we could imagine a non-breaking solution exposing two methods, in `src/SchemaRegistry.ts`:

```ts
interface DecodedMessage {
  payload: any;
  registryId: number;
}

// [...]

  public async decodeWithRegistryInformation(buffer: Buffer): Promise<DecodedMessage> {
    if (!Buffer.isBuffer(buffer)) {
      throw new ConfluentSchemaRegistryArgumentError('Invalid buffer')
    }

    const { magicByte, registryId, payload } = decode(buffer)
    if (Buffer.compare(MAGIC_BYTE, magicByte) !== 0) {
      throw new ConfluentSchemaRegistryArgumentError(
        `Message encoded with magic byte ${JSON.stringify(magicByte)}, expected ${JSON.stringify(
          MAGIC_BYTE,
        )}`,
      )
    }

    const schema = await this.getSchema(registryId)
    return {
      payload: schema.fromBuffer(payload),
      registryId,
    }
  }

  public async decode(buffer: Buffer): Promise<any> {
    const { payload } = await this.decodeWithRegistryInformation(buffer);
    return payload;
  }
```

Thanks 👋

**Comment by Nevon** [comment]
Can you expand a little bit on the use-case of this? I'm not sure I'm sold on the idea of exposing another method that does exactly the same thing as decode, except it also returns the registryId. If anything, I think I would be more inclined to expose the `wireencoder` and `wiredecoder` (maybe under some better names).

If this is not really a common use-case, I think I would advise that you just read the registryId yourselves, since it's part of the Confluent wire format. Getting the registryId is as simple as just reading an int32 from the message at a specific offset: https://github.com/kafkajs/confluent-schema-registry/blob/54584f9b13ac7f4c38e6dde5670412dedac775ea/src/wireDecoder.ts#L3

**Comment by ThomasFerro** [comment]
We consume data from a topic with no compatibility policy, to avoid creating new topics for every breaking change. When consuming the topic, we run our custom "version manager" one each message. For instance, we check if the new data is `undefined` to know if the message is in an old version.

This way of checking versions shows his limits now that we have more than 10 versions, with complex diffs between versions.

It will be much easier if we can know the version in which the message was encoded and apply data migration from there, instead of trying to guess the version.

The solution with the new method was only to avoid breaking change for people already using `decode`.

I think that we will use your solution, thanks for providing it! Please let me know if the PR and issue can be close or if they still may be relevant.

**Comment by Nevon** [comment]
I think we should close the current PR. If more people have this need, I would be open to a PR that adds a `getRegistryId(buffer: Buffer): Number` method, which just uses the `wiredecoder` to grab the registry id from the payload.
