### ISSUE TITLE
Using string as a field's default value in AVRO schema when null and string are defined in field type

### ISSUE THREAD

**Issue by bajdzun** [kafkajs/confluent-schema-registry#138]
Hello guys,

Thanks for the great work you put in this project!

We have a kafkajs consumer, consuming AVRO messages from kafka topic and decoding them with your library.

Pretty straightforward setup, works great except for one case.

In some AVRO schemas we have the following field definition:
```
{
    "name": "exampleField",
    "type": ["null","string"],
    "default": "VALUE1",
    "doc": "Allowed values ['VALUE1', 'VALUE2']"
}
```
When we try to decode schema with your library, we are getting this error `ConfluentSchemaRegistryArgumentError: invalid "null": "VALUE1"`

We checked all schemas and found out that field definition from above breaks decoder because it expects `null` to be default value because `null` is listed in `type`

Can you add support for also allowing other types in default when they are defined in field `type`? Why restricting to `null` if multiple types are allowed?

If you need any more information, I'm happy to provide them.

Cheers,
Marko

**Comment by iAlex97** [comment]
If allowed values for your `exampleField` are `['VALUE1', 'VALUE2']` why do you need to define its type as a union of `["null","string"]`?

In avro, the default type for a union is the first one you define, hence defaulting a value to a non null string will collide with your definition resulting in the error that you get.

If allowed values are in fact `['VALUE1', 'VALUE2', null]`, simply switching the type definition to `["string", "null"]` should solve your problem, otherwise I'd suggest dropping the `null` from the type.

**Comment by bajdzun** [comment]
Hey @iAlex97 thanks for the reply!
It appears that some of our schemas didn't follow avro specifications for union types as you mentioned, so we changed that and everything works fine now, so I will close this issue.

Cheers,
Marko
