### ISSUE TITLE
This library is still maintained?

### ISSUE THREAD

**Issue by zion03** [kafkajs/confluent-schema-registry#215]
Hello there! 

First, thanks for all of your work and this library.

Just one question:
Who can confirm that this library is still maintained?
Would be nice to hear a responsible person for this repo or at least a person who has access to merge PR.

Reason:
Many useful changes are available in PRs.
For example, one of them https://github.com/kafkajs/confluent-schema-registry/pull/197 is approved and ready to merge.

**Comment by hilleer** [comment]
@zion03 FYI I think the linked pull request are reviewed and approved by _external_ contributors, not someone directly related to or included as "contributors" of this project 🙂

**Comment by Nevon** [comment]
It's "maintained" in the sense that I'm still alive, but it's poorly maintained because I'm just one guy who doesn't have enough time and energy to maintain both this library as well as KafkaJS to the level they would need. I don't personally use either of the libraries for anything I do, although the organization I work for does, so if there are any security issues or some other kind of issue that affects my organization's usage that would likely shift my priorities.

I would love to have other users step up and take on more maintenance tasks. It's really not an insignificant amount of work that's required every single week to keep up. You don't need any special permissions to be able to triage issues, discuss proposals and review pull requests. Regarding #197, it doesn't look like people have been reviewing that properly and are using the "approve" button as a "'I want this functionality'-vote button", since no one seems to have found anything to provide feedback on. 😉 

If a community member were to display a consistent behavior of quality contributions in the form of triage/reviewing/documenting/debugging, I would be happy to grant them official maintainer status so that they can merge things to master and make releases, once I trust they're not gonna start sending `process.env` to the FSB or something.

**Comment by zion03** [comment]
Thanks for your answer!

For now, I can confirm that changes in PR help to work with `import` in _protobuf_ correctly.
I'll check discussion in PR and maybe can help.

And thanks again for your hard work!
